/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wipdev.tutorbot;

import io.javalin.Javalin;
import io.javalin.http.Context;
import io.javalin.http.Handler;
import org.jetbrains.annotations.NotNull;
import org.json.JSONObject;

import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;

public class App {


    private Map<String,RequestHandler> handlers = new HashMap<>();

    private Javalin javalin;


    public App() {
        javalin = Javalin.create(config -> {
            config.addStaticFiles("/public");
        });

        javalin.start(8080);

        javalin.post("request", ctx -> {
            ctx.result(handleRequest(URLDecoder.decode(ctx.queryString(), StandardCharsets.UTF_8.toString())));
        });

        initializeHandlers();
    }



    private void initializeHandlers() {
        handlers.put("test",request -> {
            JSONObject object = new JSONObject();
            object.put("key","testResponse");
            object.put("message","Hello World back !");
            return object;
        });

        handlers.put("getQuestions",new QuestionManager());
    }


    private String handleRequest(String decode) {
        JSONObject request = new JSONObject(decode);
        JSONObject errorResponse = new JSONObject();
        errorResponse.put("key","error");
        if(request !=null){
            String key = request.getString("key");
            if(key != null){
                if(handlers.containsKey(key)){
                    return handlers.get(key).handleRequest(request).toString();
                }else {
                    errorResponse.put("message","Request Handlers does not contain key="+key);
                }
            }else{
                errorResponse.put("message","Key can not be null");
            }
        }else {
            errorResponse.put("message","Request is not an valid JSON Object. ->"+decode);
        }

        return errorResponse.toString();
    }


    public static void main(String[] args) {
        new App();
    }
}
