/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.wip.tutorbot;

import de.wip.tutorbot.persistent.DatabaseHandler;

import javax.mail.MessagingException;
import java.io.IOException;
import java.sql.SQLException;

public class App {

    private Server server;

    public App() {
        try {
            DatabaseHandler.connect();
            System.out.println("Connected to Database!");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        server = new Server(1337);

    }

    public static void main(String[] args) {
        new App();
    }
}
